version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=gochat
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=gochat
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/gochat_dump.sql:/docker-entrypoint-initdb.d/gochat_dump.sql
volumes:
  postgres_data:
